services:
  mongo:
    image: 'mongo:4.2.21'
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tucarbure
      - MONGO_INITDB_ROOT_PASSWORD=tucarbure
    ports:
      - '27018:27018'

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - C:\Users\skalu\Desktop\Projet3-cda\TuCarbureAPI\docker\prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
