services:
  mongo:
    image: 'mongo:latest'
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tucarbure
      - MONGO_INITDB_ROOT_PASSWORD=tucarbure
    ports:
      - '27018:27018'